### ISSUE TITLE
Where can I get the Datasets "/FNS2022/English/training/"

### ISSUE THREAD

**Issue by Zerhan99** [neeleshkshukla/DiMSum_FNP_2022#1]
Hi Shukla,

I am very interested in FNP-2022-FinToC, But I dont know where should I download the datasets. Could you give me some advice? Or could it suitable for senting the datasets to me?

**Comment by neeleshkshukla** [comment]
Hi, the dataset for FinTOC was provided to participants and not availble publicly. If you're interested, please reach out to FinTOC organizers. The details could be found here. http://wp.lancs.ac.uk/cfie/fintoc2022/
